-- name: SetRelyingParty :exec
INSERT INTO webauthn_data.realm (realm_id, rp_id, rp_name, attachment, user_verification,
                                 attestation, attestation_formats, hints, algorithms, extensions,
                                 timeout, origins, origin_enforced, cross_origin_enforced,
                                 top_origins, rp_id_hash_mismatch_allowed, backup_flags_enforced,
                                 backup_eligibility_enforced, sign_count_enforced,
                                 uv_transition_allowed, allowed_attestation_formats,
                                 allowed_attestation_types, trust_anchors,
                                 intermediate_certificates, revocation_mode,
                                 certificate_revocation_lists, attestation_downgrade_allowed,
                                 login_attestation_enforced)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
        $20, $21, $22, $23, $24, $25, $26, $27, $28)
ON CONFLICT (realm_id, rp_id) DO UPDATE
   SET rp_name = EXCLUDED.rp_name,
       attachment = EXCLUDED.attachment,
       user_verification = EXCLUDED.user_verification,
       attestation = EXCLUDED.attestation,
       attestation_formats = EXCLUDED.attestation_formats,
       hints = EXCLUDED.hints,
       algorithms = EXCLUDED.algorithms,
       extensions = EXCLUDED.extensions,
       timeout = EXCLUDED.timeout,
       origins = EXCLUDED.origins,
       origin_enforced = EXCLUDED.origin_enforced,
       cross_origin_enforced = EXCLUDED.cross_origin_enforced,
       top_origins = EXCLUDED.top_origins,
       rp_id_hash_mismatch_allowed = EXCLUDED.rp_id_hash_mismatch_allowed,
       backup_flags_enforced = EXCLUDED.backup_flags_enforced,
       backup_eligibility_enforced = EXCLUDED.backup_eligibility_enforced,
       sign_count_enforced = EXCLUDED.sign_count_enforced,
       uv_transition_allowed = EXCLUDED.uv_transition_allowed,
       allowed_attestation_formats = EXCLUDED.allowed_attestation_formats,
       allowed_attestation_types = EXCLUDED.allowed_attestation_types,
       trust_anchors = EXCLUDED.trust_anchors,
       intermediate_certificates = EXCLUDED.intermediate_certificates,
       revocation_mode = EXCLUDED.revocation_mode,
       certificate_revocation_lists = EXCLUDED.certificate_revocation_lists,
       attestation_downgrade_allowed = EXCLUDED.attestation_downgrade_allowed,
       login_attestation_enforced = EXCLUDED.login_attestation_enforced;
